package com.huabuy.repositories.pojo;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBDocument;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;

@DynamoDBDocument
public class ItemPojo {

    private String item;
    private String originalPrice;
    private int id;

    @DynamoDBAttribute(attributeName="originalPrice")
    public String getOriginalPrice() {
        return originalPrice;
    }

    public void setOriginalPrice(String originalPrice) {
        this.originalPrice = originalPrice;
    }

    @DynamoDBAttribute(attributeName="item_name")
    public String getItem() {
        return item;
    }

    public void setItem(String item) {
        this.item = item;
    }

    @DynamoDBAttribute(attributeName="id")
    public int getId() {
        return id;
    }

    public void setId(int id) {
        this.id = id;
    }
}
